import { FormEvent, useMemo, useState } from "react";
import { BarChart3, BookOpenCheck, BrainCircuit, CalendarDays, CheckCircle2, ChevronRight, Languages, LayoutDashboard, Loader2, Palette, ShieldCheck, Sparkles, X } from "lucide-react";

type Mode = "whiteboard" | "performance" | "adaptive" | "language" | "curriculum" | "safety" | "revision";
type Result = {
  title: string; summary: string; visualType: "graph" | "equation" | "flow" | "diagram" | "none";
  visualLabels: string[]; visualData: number[];
  insights: { label: string; detail: string; status: string; value: number }[];
  steps: { day: string; topic: string; activity: string; duration: string }[];
};

const tools = [
  { id: "whiteboard" as Mode, title: "Interactive Whiteboard", short: "Watch diagrams, equations, graphs and worked solutions unfold step by step—not as a wall of text.", outcome: "Visual explanation + solution steps", icon: Palette, theme: "from-blue-600 to-cyan-500", bg: "bg-blue-50", text: "text-blue-700" },
  { id: "performance" as Mode, title: "AI Performance Analysis", short: "Turn quiz evidence into chapter-level strengths, misconceptions and precise concept gaps.", outcome: "Weakness map + diagnostic actions", icon: BarChart3, theme: "from-violet-600 to-fuchsia-500", bg: "bg-violet-50", text: "text-violet-700" },
  { id: "adaptive" as Mode, title: "Personalized Learning", short: "Get easier examples, deeper challenges and a learning sequence matched to your pace and present level.", outcome: "Adaptive path + next best lesson", icon: BrainCircuit, theme: "from-emerald-600 to-teal-500", bg: "bg-emerald-50", text: "text-emerald-700" },
  { id: "language" as Mode, title: "Multilingual AI", short: "Switch explanations, chat and voice between English, Hindi and natural Hinglish without losing key terms.", outcome: "Learn in the language you think in", icon: Languages, theme: "from-orange-500 to-amber-400", bg: "bg-orange-50", text: "text-orange-700" },
  { id: "curriculum" as Mode, title: "Curriculum-aware AI", short: "Keep answers aligned to your class, board, expected depth, textbook sequence and exam outcomes.", outcome: "Board-aligned concept roadmap", icon: BookOpenCheck, theme: "from-indigo-600 to-blue-500", bg: "bg-indigo-50", text: "text-indigo-700" },
  { id: "safety" as Mode, title: "Content Safety AI", short: "Maintain age-appropriate, private and educational conversations with honest limits and safe redirection.", outcome: "Protected learning mode—always on", icon: ShieldCheck, theme: "from-slate-700 to-slate-500", bg: "bg-slate-100", text: "text-slate-700" },
  { id: "revision" as Mode, title: "Custom Revision Planner", short: "Convert weak chapters, exam dates and available study time into a realistic daily revision calendar.", outcome: "Prioritized calendar + daily tasks", icon: CalendarDays, theme: "from-rose-600 to-orange-500", bg: "bg-rose-50", text: "text-rose-700" },
];

const subjects = ["Mathematics", "Science", "Physics", "Chemistry", "Biology", "English", "Hindi", "Social Science"];
const empty: Result = { title: "", summary: "", visualType: "none", visualLabels: [], visualData: [], insights: [], steps: [] };

export default function StudentIntelligenceSuite({ grade, board, language, level, onLanguageChange }: { grade: string; board: string; language: string; level: string; onLanguageChange: (value: string) => void }) {
  const [active, setActive] = useState<Mode | null>(null);
  const [subject, setSubject] = useState("Mathematics");
  const [topic, setTopic] = useState("");
  const [context, setContext] = useState("");
  const [result, setResult] = useState<Result>(empty);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const tool = tools.find((item) => item.id === active);

  const open = (mode: Mode) => { setActive(mode); setResult(empty); setError(""); setTopic(""); setContext(""); };
  const close = () => { setActive(null); setResult(empty); setError(""); };
  const promptLabel = active === "whiteboard" ? "What should the AI draw?" : active === "performance" ? "Which chapters should be analysed?" : active === "adaptive" ? "What do you want to master?" : active === "curriculum" ? "Topic or textbook chapter" : "Subjects or chapters to revise";
  const placeholder = active === "whiteboard" ? "e.g. Draw a graph of y = 2x + 1" : active === "performance" ? "e.g. Fractions, decimals and algebra" : active === "revision" ? "e.g. Mathematics: Algebra; Science: Light" : "e.g. Photosynthesis";

  const generate = async (event: FormEvent) => {
    event.preventDefault(); if (!active || !topic.trim()) return;
    setLoading(true); setError(""); setResult(empty);
    try {
      const response = await fetch("/api/student-tool", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: active, grade, board, language, level, subject, topic, context }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Could not create this learning tool.");
      setResult(data.result);
    } catch (value) { setError(value instanceof Error ? value.message : "Something went wrong."); }
    finally { setLoading(false); }
  };

  return <section className="rounded-[30px] border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#004aad]">My intelligent learning desk</p><h2 className="mt-1 font-poppins text-2xl font-extrabold">Seven tools, built for seven different jobs</h2><p className="mt-2 text-sm text-slate-500">Configured for {board} Class {grade} · {language} · {level} level</p></div><span className="w-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-extrabold text-emerald-700">Safe student mode</span></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2">
      {tools.map((item, index) => { const Icon = item.icon; return <button key={item.id} onClick={() => open(item.id)} className={`group relative min-h-[260px] overflow-hidden rounded-[24px] border p-6 text-left transition hover:-translate-y-1 hover:shadow-xl ${index === 0 ? "border-blue-200 md:col-span-2" : "border-slate-200"}`}><div className={`absolute inset-x-0 top-0 h-1.5 bg-gradient-to-r ${item.theme}`} /><div className="flex items-start justify-between"><span className={`flex h-14 w-14 items-center justify-center rounded-2xl ${item.bg} ${item.text}`}><Icon className="h-7 w-7" /></span><span className="rounded-full bg-slate-50 px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-slate-400">AI workspace</span></div><h3 className="mt-6 font-poppins text-xl font-extrabold">{item.title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">{item.short}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className={`text-xs font-extrabold ${item.text}`}>{item.outcome}</span><span className={`flex items-center gap-1 text-xs font-extrabold ${item.text}`}>Launch <ChevronRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></button>; })}
    </div>

    {active && tool && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/65 p-2 backdrop-blur-sm sm:p-5" role="dialog" aria-modal="true">
      <div className="flex max-h-[95vh] w-full max-w-6xl flex-col overflow-hidden rounded-[28px] bg-white shadow-2xl">
        <header className={`flex items-center justify-between bg-gradient-to-r ${tool.theme} px-5 py-4 text-white sm:px-7`}><div className="flex items-center gap-3"><tool.icon className="h-6 w-6" /><div><h2 className="font-poppins text-xl font-extrabold">{tool.title}</h2><p className="text-xs text-white/80">{board} · Class {grade} · {subject}</p></div></div><button onClick={close} className="rounded-xl bg-white/15 p-2"><X className="h-5 w-5" /></button></header>
        <div className="overflow-y-auto p-5 sm:p-7">
          {active === "language" ? <LanguageWorkspace language={language} onChange={onLanguageChange} /> : active === "safety" ? <SafetyWorkspace /> : <div className="grid gap-6 lg:grid-cols-[320px_minmax(0,1fr)]">
            <form onSubmit={generate} className="h-fit rounded-2xl border border-slate-200 bg-slate-50 p-5"><label className="text-xs font-extrabold uppercase tracking-wider text-slate-500">Subject<select value={subject} onChange={(e) => setSubject(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm font-bold text-slate-800">{subjects.map((name) => <option key={name}>{name}</option>)}</select></label><label className="mt-5 block text-sm font-extrabold">{promptLabel}<textarea required value={topic} onChange={(e) => setTopic(e.target.value)} rows={3} placeholder={placeholder} className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-white p-3 text-sm font-normal outline-none focus:border-blue-400" /></label><label className="mt-4 block text-sm font-extrabold">{active === "performance" ? "Your evidence" : active === "revision" ? "Exam date and study time" : "What I already know (optional)"}<textarea value={context} onChange={(e) => setContext(e.target.value)} rows={4} placeholder={active === "performance" ? "Paste recent scores or write which questions were difficult. The AI will not guess missing data." : active === "revision" ? "e.g. Exam: 2026-09-20, 45 minutes daily, Sunday off" : "Tell the AI what feels easy or difficult."} className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-white p-3 text-sm font-normal outline-none focus:border-blue-400" /></label>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<button disabled={loading || !topic.trim()} className={`mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r ${tool.theme} px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50`}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{loading ? "Building workspace…" : active === "performance" ? "Analyse evidence" : active === "revision" ? "Build calendar" : "Create with AI"}</button></form>
            <ToolOutput mode={active} result={result} loading={loading} />
          </div>}
        </div>
      </div>
    </div>}
  </section>;
}

function ToolOutput({ mode, result, loading }: { mode: Mode; result: Result; loading: boolean }) {
  if (loading) return <div className="flex min-h-[440px] items-center justify-center rounded-2xl border border-dashed border-blue-200 bg-blue-50/40"><div className="text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-[#004aad]" /><p className="mt-3 text-sm font-bold text-slate-600">AI is preparing your {mode} workspace…</p></div></div>;
  if (!result.title) return <div className="flex min-h-[440px] items-center justify-center rounded-2xl border border-dashed border-slate-300"><div className="max-w-sm text-center"><LayoutDashboard className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 font-extrabold">Your workspace will appear here</p><p className="mt-1 text-sm leading-6 text-slate-500">Enter specific information so the AI can create an accurate, class-level result.</p></div></div>;
  return <div className="space-y-5"><div><h3 className="font-poppins text-2xl font-extrabold">{result.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{result.summary}</p></div>{mode === "whiteboard" && <VisualBoard result={result} />}{mode === "performance" && <PerformanceBoard result={result} />}{mode === "adaptive" && <LearningPath result={result} />}{mode === "curriculum" && <CurriculumMap result={result} />}{mode === "revision" && <RevisionCalendar result={result} />}</div>;
}

function VisualBoard({ result }: { result: Result }) {
  const points = result.visualData.length ? result.visualData : [1, 3, 2, 5, 4]; const max = Math.max(...points, 1);
  return <div className="overflow-hidden rounded-2xl border-4 border-slate-700 bg-[#102f28] text-white shadow-xl"><div className="flex items-center justify-between border-b border-white/15 px-5 py-3"><span className="text-xs font-bold uppercase tracking-widest text-emerald-200">Live concept board</span><span className="text-xs text-white/60">{result.visualType}</span></div><div className="min-h-72 p-6">{result.visualType === "graph" ? <svg viewBox="0 0 500 230" className="h-64 w-full"><path d="M45 10V195H485" stroke="white" strokeWidth="3" fill="none"/><polyline points={points.map((v, i) => `${55 + i * (410 / Math.max(points.length - 1, 1))},${190 - (v / max) * 155}`).join(" ")} fill="none" stroke="#fbbf24" strokeWidth="5" strokeLinejoin="round"/>{points.map((v, i) => <circle key={i} cx={55 + i * (410 / Math.max(points.length - 1, 1))} cy={190 - (v / max) * 155} r="6" fill="#fb923c" />)}</svg> : <div className="flex min-h-56 flex-wrap items-center justify-center gap-3">{result.visualLabels.map((label, i) => <div key={i} className="flex items-center gap-3"><span className="rounded-xl border-2 border-amber-300 px-4 py-3 text-center font-bold text-amber-100">{label}</span>{i < result.visualLabels.length - 1 && <ChevronRight className="text-emerald-300" />}</div>)}</div>}</div><ol className="grid gap-2 bg-black/15 p-5 sm:grid-cols-2">{result.steps.map((step, i) => <li key={i} className="rounded-xl bg-white/10 p-3 text-sm"><strong className="text-amber-300">Step {i + 1}: </strong>{step.activity}</li>)}</ol></div>;
}

function PerformanceBoard({ result }: { result: Result }) { return <div><div className="grid gap-3 sm:grid-cols-2">{result.insights.map((item, i) => <div key={i} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between"><h4 className="font-extrabold">{item.label}</h4><span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-extrabold text-violet-700">{item.status}</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-gradient-to-r from-violet-600 to-fuchsia-400" style={{ width: `${Math.max(5, Math.min(100, item.value))}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-500">{item.detail}</p></div>)}</div><h4 className="mt-5 font-extrabold">Recommended diagnostic</h4><div className="mt-3 space-y-2">{result.steps.map((step, i) => <div key={i} className="flex gap-3 rounded-xl bg-slate-50 p-3"><span className="font-extrabold text-violet-700">{i + 1}</span><div><p className="text-sm font-bold">{step.topic}</p><p className="text-xs text-slate-500">{step.activity}</p></div></div>)}</div></div>; }
function LearningPath({ result }: { result: Result }) { return <div className="relative space-y-3 before:absolute before:bottom-5 before:left-5 before:top-5 before:w-0.5 before:bg-emerald-200">{result.steps.map((step, i) => <div key={i} className="relative flex gap-4"><span className="z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-600 font-extrabold text-white">{i + 1}</span><div className="flex-1 rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4"><div className="flex justify-between gap-3"><h4 className="font-extrabold">{step.topic}</h4><span className="text-xs font-bold text-emerald-700">{step.duration}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{step.activity}</p></div></div>)}</div>; }
function CurriculumMap({ result }: { result: Result }) { return <div className="grid gap-3 sm:grid-cols-2">{result.steps.map((step, i) => <div key={i} className="rounded-2xl border border-indigo-100 bg-gradient-to-br from-indigo-50 to-white p-4"><span className="text-xs font-extrabold uppercase tracking-widest text-indigo-600">Stage {i + 1}</span><h4 className="mt-2 font-extrabold">{step.topic}</h4><p className="mt-2 text-sm leading-6 text-slate-600">{step.activity}</p><p className="mt-3 text-xs font-bold text-indigo-700">{step.duration}</p></div>)}</div>; }
function RevisionCalendar({ result }: { result: Result }) { return <div className="overflow-hidden rounded-2xl border border-slate-200"><div className="grid grid-cols-[110px_1fr_90px] bg-rose-600 px-4 py-3 text-xs font-extrabold uppercase text-white"><span>Date</span><span>Revision task</span><span>Time</span></div>{result.steps.map((step, i) => <div key={i} className="grid grid-cols-[110px_1fr_90px] gap-2 border-t border-slate-100 px-4 py-4 text-sm"><span className="font-extrabold text-rose-700">{step.day}</span><span><strong className="block">{step.topic}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{step.activity}</span></span><span className="text-xs font-bold text-slate-500">{step.duration}</span></div>)}</div>; }

function LanguageWorkspace({ language, onChange }: { language: string; onChange: (value: string) => void }) { const samples = { English: ["Simple explanations", "Indian examples", "English voice"], Hindi: ["सरल हिंदी में समझाइए", "मुख्य शब्द English में", "हिंदी आवाज़"], Hinglish: ["Easy Hinglish explanation", "Important terms in English", "Natural Indian voice"] }; return <div className="mx-auto max-w-4xl"><div className="grid gap-4 sm:grid-cols-3">{Object.entries(samples).map(([name, items]) => <button key={name} onClick={() => onChange(name)} className={`rounded-2xl border p-5 text-left transition ${language === name ? "border-orange-400 bg-orange-50 ring-4 ring-orange-50" : "border-slate-200"}`}><Languages className={`h-6 w-6 ${language === name ? "text-orange-600" : "text-slate-400"}`} /><h3 className="mt-4 text-lg font-extrabold">{name}</h3><ul className="mt-3 space-y-2 text-sm text-slate-500">{items.map((item) => <li key={item}>• {item}</li>)}</ul></button>)}</div><div className="mt-6 rounded-2xl bg-gradient-to-r from-orange-500 to-amber-400 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-100">Active tutor language</p><p className="mt-2 text-3xl font-extrabold">{language}</p><p className="mt-2 text-sm text-orange-50">Chat replies, voice recognition, spoken answers and new AI resources will use this language.</p></div></div>; }
function SafetyWorkspace() { const cards = [["Educational boundaries", "The tutor redirects unsafe or age-inappropriate requests to a safe learning explanation."], ["Privacy protection", "Students are never asked for phone numbers, addresses, passwords, photos or private contact details."], ["Honest learning", "The AI teaches methods and gives hints instead of helping students cheat in assessed work."], ["Trusted adults", "Urgent safety concerns are directed to a parent, teacher or appropriate emergency support."], ["Uncertainty labels", "The AI says when it is unsure and recommends checking important answers with a teacher or textbook."], ["No secret relationships", "The tutor does not encourage secrecy, emotional dependency or replacing real teachers and family."]]; return <div><div className="rounded-2xl bg-slate-900 p-6 text-white"><ShieldCheck className="h-10 w-10 text-emerald-400" /><h3 className="mt-4 text-2xl font-extrabold">Protected learning mode is always on</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">These protections run in every tutor conversation and generated learning resource.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{cards.map(([title, body]) => <div key={title} className="flex gap-3 rounded-2xl border border-slate-200 p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600" /><div><h4 className="font-extrabold">{title}</h4><p className="mt-1 text-xs leading-5 text-slate-500">{body}</p></div></div>)}</div></div>; }
